# Generated by Django 4.0.6 on 2022-08-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_by',
            field=models.CharField(default='Anonymous User', max_length=100),
        ),
    ]
