# Generated by Django 4.0.6 on 2022-08-08 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_rename_new_notice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
