# Generated by Django 4.0.6 on 2022-08-26 00:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notice',
            name='image',
            field=models.ImageField(null=True, upload_to='news/images/'),
        ),
    ]
