# Generated by Django 4.0.6 on 2022-08-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_notice_date_alter_notice_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='created_by',
            field=models.CharField(default='Anonymous User', max_length=100),
        ),
    ]
