# Generated by Django 4.0.6 on 2022-08-07 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_creation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nick',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nombre',
            new_name='username',
        ),
    ]
