# Generated by Django 4.0.6 on 2022-08-07 06:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_nick_user_name_rename_nombre_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
